server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/course
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always